package com.fsy.tool;

import com.fsy.tool.dto.UserModelBean;
import com.fsy.tool.util.CollectionUtil;
import com.fsy.tool.util.StringUtil;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vincent
 */
public class Main extends javax.swing.JFrame {

    private List<UserModelBean> users = new ArrayList<>();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        this.setTitle("至善点赞习题V1.0");
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        courseLabel = new javax.swing.JLabel("课程编码");
        courseField = new JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("导入学生对应账号");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton2ActionPerformed(evt);
                } catch (IOException e) {
                    JOptionPane.showOptionDialog( Main.this , "导入失败 " + e.getMessage() , "通知" , OK_CANCEL_OPTION , QUESTION_MESSAGE , null , null , null);
                    return;
                    //e.printStackTrace();
                }
            }
        });

        jButton3.setText("开始");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDo();
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addComponent(courseLabel)
                                        .addComponent(courseField)
                                        .addComponent(jButton3)

                                )

                        )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(courseLabel)
                                .addGap(18 ,18 ,18)
                                .addComponent(courseField)
                                .addGap(18 ,18 ,18)
                                .addComponent(jButton3)
                                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }

    private void startDo() {
        if(CollectionUtil.isEmpty(users)){
            JOptionPane.showMessageDialog(this, "未导入学生账号，请导入后重新操作");
            return;
        }
        if(StringUtil.isEmpty(courseField.getText())){
            JOptionPane.showMessageDialog(this, "未填写课程编码，请填写后重新操作");
            return;
        }

        new MutilpleUserApi(users , courseField.getText().trim() ).start();


    }


    public void setDesktopIfWindows(JFileChooser chooser){
        chooser.setCurrentDirectory(new File(System.getenv("HOME") + "/Desktop"));
        chooser.setDragEnabled(true);
    }
    private void jButton2ActionPerformed(ActionEvent evt) throws IOException {
        JFileChooser jFileChooser = new JFileChooser();
        setDesktopIfWindows(jFileChooser);
        jFileChooser.showOpenDialog(this);
        if(jFileChooser.getSelectedFile() != null){
            users.clear();
            String filePath = jFileChooser.getSelectedFile().getAbsolutePath();
            BufferedReader br = new BufferedReader(new FileReader(new File(filePath)));
            String userStr = "";
            int line = 0;
            while( (userStr = br.readLine()) != null){
                line = line + 1;
                String [] userSplited = userStr.split(",");

                if(userSplited.length !=2 ){
                    JOptionPane.showOptionDialog( Main.this , "用户导入失败 导入格式不正确! 第" + line +"行"  , "错误" , OK_CANCEL_OPTION , QUESTION_MESSAGE , null , null , null);
                    System.exit(0);
                }

                String username = java.net.URLEncoder.encode(userSplited[0].trim(), "utf-8");;
                String password = userSplited[1].trim();
                users.add(UserModelBean.builder()
                        .username(username)
                        .password(password).build());
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    //导入学生账号
    private javax.swing.JButton jButton2;
    //开始按钮
    private javax.swing.JButton jButton3;

    //课程label
    private javax.swing.JLabel courseLabel;

    //课程id
    private javax.swing.JTextField courseField;



    // End of variables declaration
}

